reviews_comments_rating
DmitriyMikhalev/api_yamdb pull request #2
Opened 2022-11-03 05:35 UTC by Not-user-1984

были сделаны модели Review, Comment в приложение reviews, так же Cериализаторы вью сеты в приложение api ,так же прописаны урлы для них

2022-11-03 07:26 UTC, DmitriyMikhalev requested changes
Правки в комментариях по строкам. Также надо удалить пустые файлы по типу admin.py.

2022-11-03 07:26 UTC, DmitriyMikhalev commented on api_yamdb/reviews/models.py
> +    text = models.TimeField()
Здесь должен быть тип TextField().

2022-11-03 07:26 UTC, DmitriyMikhalev commented on api_yamdb/reviews/models.py
> +
Нужно отсортировать все классы и атрибуты по алфавиту.

2022-11-03 08:39 UTC, Not-user-1984 commented on api_yamdb/api/views.py
> +        serializer.save(author=self.request.user, title=title)
а тут проверка не на уровне Пермишина? я просто их пока не прописывал  и прописывать ли мне их?

2022-11-03 08:43 UTC, Not-user-1984 commented on api_yamdb/reviews/models.py
> +
и тут модели должны быть первые?

2022-11-03 08:58 UTC, DmitriyMikhalev commented on api_yamdb/api/views.py
> +        serializer.save(author=self.request.user, title=title)
Если на уровне проекта установлено ограничение IsAuthenticated, то все ок

2022-11-03 08:58 UTC, DmitriyMikhalev commented on api_yamdb/reviews/models.py
> +
Не понял вопрос

2022-11-03 09:06 UTC, DmitriyMikhalev commented on api_yamdb/reviews/models.py
> +
Да. В целом нужно все и везде сортировать по алфавиту

2022-11-03 09:07 UTC, Not-user-1984 commented on api_yamdb/api/views.py
> +        serializer.save(author=self.request.user, title=title)
ну анонимы не могут создавать это будет на уровне пермишина, а вот как мы их будем задавать, можно на уровне проекта

2022-11-03 09:17 UTC, DmitriyMikhalev commented on api_yamdb/api/views.py
> +        serializer.save(author=self.request.user, title=title)
Сейчас в мастере на уровне проекта IsAuthenticated. Если не было идеи менять, то все ок

2022-11-05 12:40 UTC, DmitriyMikhalev approved these changes

2022-11-05 12:41 UTC, merged